# Generated by Django 4.0.3 on 2022-03-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tontine', models.CharField(choices=[('52 USDT', 'Tontine 52 USDT'), ('302 USDT', 'Tontine 302 USDT'), ('502 USDT', 'Tontine 502 USDT'), ('1002 USDT', 'Tontine 1002 USDT'), ('2002 USDT', 'Tontine 2002 USDT')], max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
